// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0yDy5jtiRCJJLxoWU6ixwgE3HZrhNmq0',
    appId: '1:27718427940:web:b5410b1df3d840aa463fb1',
    messagingSenderId: '27718427940',
    projectId: 'intermessh',
    authDomain: 'intermessh.firebaseapp.com',
    storageBucket: 'intermessh.appspot.com',
    measurementId: 'G-X91J1Y4WX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVn8-IJrmDuvrXbUZA3epVmhTRKFSNGt8',
    appId: '1:27718427940:android:7620356b201e66fb463fb1',
    messagingSenderId: '27718427940',
    projectId: 'intermessh',
    storageBucket: 'intermessh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2QrZ3rh1bslhxdGNE7Ng91LGeo7oXiQk',
    appId: '1:27718427940:ios:bcbb575aec61dc8b463fb1',
    messagingSenderId: '27718427940',
    projectId: 'intermessh',
    storageBucket: 'intermessh.appspot.com',
    androidClientId: '27718427940-urr18o8d6s1bgijtatcmqmggacth0ven.apps.googleusercontent.com',
    iosClientId: '27718427940-ajug2fhm4g985343tp6muba2m72vq6qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.outcome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2QrZ3rh1bslhxdGNE7Ng91LGeo7oXiQk',
    appId: '1:27718427940:ios:bcbb575aec61dc8b463fb1',
    messagingSenderId: '27718427940',
    projectId: 'intermessh',
    storageBucket: 'intermessh.appspot.com',
    androidClientId: '27718427940-urr18o8d6s1bgijtatcmqmggacth0ven.apps.googleusercontent.com',
    iosClientId: '27718427940-ajug2fhm4g985343tp6muba2m72vq6qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.outcome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0yDy5jtiRCJJLxoWU6ixwgE3HZrhNmq0',
    appId: '1:27718427940:web:cc30fc7f39794dce463fb1',
    messagingSenderId: '27718427940',
    projectId: 'intermessh',
    authDomain: 'intermessh.firebaseapp.com',
    storageBucket: 'intermessh.appspot.com',
    measurementId: 'G-MLWQHRJR1V',
  );
}
